### ISSUE TITLE
Freezing on a bigger codebase

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#116]
**Describe the bug**
Running the analyzer on a bigger codebase eats a lot of cpu and freezes at some point

**To Reproduce**
`yarn analyze /path/to/bigger/vue/project`

**What is the output you are getting?**

No output for minutes, end then

```
file:///home/rrd/public_html/vue-mess-detector/dist/vue-mess-detector.es.js:1236
  ), r = n.content.match(o);
           ^

TypeError: Cannot read properties of null (reading 'content')
    at $s (file:///home/rrd/public_html/vue-mess-detector/dist/vue-mess-detector.es.js:1236:12)
    at Ys (file:///home/rrd/public_html/vue-mess-detector/dist/vue-mess-detector.es.js:1564:174)
    at file:///home/rrd/public_html/vue-mess-detector/dist/vue-mess-detector.es.js:1594:5
    at Tt (file:///home/rrd/public_html/vue-mess-detector/dist/vue-mess-detector.es.js:1583:102)
    at Tt (file:///home/rrd/public_html/vue-mess-detector/dist/vue-mess-detector.es.js:1583:69)
    at Tt (file:///home/rrd/public_html/vue-mess-detector/dist/vue-mess-detector.es.js:1583:69)
    at Hs (file:///home/rrd/public_html/vue-mess-detector/dist/vue-mess-detector.es.js:1590:150)
    at Object.handler (file:///home/rrd/public_html/vue-mess-detector/dist/vue-mess-detector.es.js:1625:90)
    at file:///home/rrd/public_html/vue-mess-detector/node_modules/yargs/build/lib/command.js:206:54
    at maybeAsyncResult (file:///home/rrd/public_html/vue-mess-detector/node_modules/yargs/build/lib/utils/maybe-async-result.js:9:15)

Node.js v20.13.0
error Command failed with exit code 1.
```

**Expected behavior**
It runs as for smaller projects

**Used version number of vue-mess-detector:**
Current development version

**Used version number of node & yarn:**
na

**Additional context**
na

**Comment by rrd108** [comment]
This project has 122 vue files

**Comment by rrd108** [comment]
It is caused by the `functionSize` rule

**Comment by rrd108** [comment]
should be handled in #119
